# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\kangsinhan\Downloads\Qt_code\PlotGUI_1031.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1533, 847)
        Dialog.setStyleSheet(_fromUtf8("background-color:white;"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(250, 40, 921, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("background-color:rgb(139, 0, 41);\n"
"color:white;\n"
"border-radius: 30px;"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.korea = QtGui.QLabel(Dialog)
        self.korea.setGeometry(QtCore.QRect(80, 30, 131, 121))
        self.korea.setText(_fromUtf8(""))
        self.korea.setObjectName(_fromUtf8("korea"))
        self.iitp = QtGui.QLabel(Dialog)
        self.iitp.setGeometry(QtCore.QRect(1200, 20, 251, 81))
        self.iitp.setText(_fromUtf8(""))
        self.iitp.setObjectName(_fromUtf8("iitp"))
        self.load_back = QtGui.QLabel(Dialog)
        self.load_back.setGeometry(QtCore.QRect(45, 176, 211, 121))
        self.load_back.setStyleSheet(_fromUtf8("background-color:qlineargradient(spread:pad, x1:0.244, y1:1, x2:0.199, y2:0.0280455, stop:0 rgba(96, 67, 67, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-width:1px;\n"
"border-color:black;\n"
"border-radius:15px;\n"
"color:black;"))
        self.load_back.setText(_fromUtf8(""))
        self.load_back.setObjectName(_fromUtf8("load_back"))
        self.analysis_back = QtGui.QLabel(Dialog)
        self.analysis_back.setGeometry(QtCore.QRect(45, 320, 211, 121))
        self.analysis_back.setStyleSheet(_fromUtf8("background-color:qlineargradient(spread:pad, x1:0.244, y1:1, x2:0.199, y2:0.0280455, stop:0 rgba(96, 67, 67, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-width:1px;\n"
"border-color:black;\n"
"border-radius:15px;\n"
"color:black;"))
        self.analysis_back.setText(_fromUtf8(""))
        self.analysis_back.setObjectName(_fromUtf8("analysis_back"))
        self.text_back = QtGui.QLabel(Dialog)
        self.text_back.setGeometry(QtCore.QRect(35, 504, 221, 316))
        self.text_back.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius:30px;\n"
"background-color:white;"))
        self.text_back.setText(_fromUtf8(""))
        self.text_back.setObjectName(_fromUtf8("text_back"))
        self.patient_info = QtGui.QLabel(Dialog)
        self.patient_info.setGeometry(QtCore.QRect(95, 524, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.patient_info.setFont(font)
        self.patient_info.setStyleSheet(_fromUtf8("color:black;"))
        self.patient_info.setAlignment(QtCore.Qt.AlignCenter)
        self.patient_info.setObjectName(_fromUtf8("patient_info"))
        self.id_text = QtGui.QLabel(Dialog)
        self.id_text.setGeometry(QtCore.QRect(45, 597, 41, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.id_text.setFont(font)
        self.id_text.setStyleSheet(_fromUtf8("color:black;"))
        self.id_text.setObjectName(_fromUtf8("id_text"))
        self.name_text = QtGui.QLabel(Dialog)
        self.name_text.setGeometry(QtCore.QRect(45, 637, 41, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name_text.setFont(font)
        self.name_text.setStyleSheet(_fromUtf8("color:black;"))
        self.name_text.setObjectName(_fromUtf8("name_text"))
        self.sex_text = QtGui.QLabel(Dialog)
        self.sex_text.setGeometry(QtCore.QRect(45, 677, 41, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sex_text.setFont(font)
        self.sex_text.setStyleSheet(_fromUtf8("color:black;"))
        self.sex_text.setObjectName(_fromUtf8("sex_text"))
        self.birth_text = QtGui.QLabel(Dialog)
        self.birth_text.setGeometry(QtCore.QRect(45, 717, 71, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.birth_text.setFont(font)
        self.birth_text.setStyleSheet(_fromUtf8("color:black;"))
        self.birth_text.setObjectName(_fromUtf8("birth_text"))
        self.date_text = QtGui.QLabel(Dialog)
        self.date_text.setGeometry(QtCore.QRect(45, 757, 51, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.date_text.setFont(font)
        self.date_text.setStyleSheet(_fromUtf8("color:black;"))
        self.date_text.setObjectName(_fromUtf8("date_text"))
        self.id = QtGui.QLabel(Dialog)
        self.id.setGeometry(QtCore.QRect(120, 597, 121, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.id.setFont(font)
        self.id.setStyleSheet(_fromUtf8("color: black;\n"
"border :0px;\n"
"background-color:rgb(255, 239, 229);"))
        self.id.setText(_fromUtf8(""))
        self.id.setObjectName(_fromUtf8("id"))
        self.name = QtGui.QLabel(Dialog)
        self.name.setGeometry(QtCore.QRect(120, 637, 121, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setStyleSheet(_fromUtf8("color: black;\n"
"border :0px;\n"
"background-color:rgb(255, 239, 229);"))
        self.name.setText(_fromUtf8(""))
        self.name.setObjectName(_fromUtf8("name"))
        self.sex = QtGui.QLabel(Dialog)
        self.sex.setGeometry(QtCore.QRect(120, 677, 121, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sex.setFont(font)
        self.sex.setStyleSheet(_fromUtf8("color: black;\n"
"border :0px;\n"
"background-color:rgb(255, 239, 229);"))
        self.sex.setObjectName(_fromUtf8("sex"))
        self.birth = QtGui.QLabel(Dialog)
        self.birth.setGeometry(QtCore.QRect(120, 717, 121, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.birth.setFont(font)
        self.birth.setStyleSheet(_fromUtf8("color: black;\n"
"border :0px;\n"
"background-color:rgb(255, 239, 229);"))
        self.birth.setText(_fromUtf8(""))
        self.birth.setObjectName(_fromUtf8("birth"))
        self.date = QtGui.QLabel(Dialog)
        self.date.setGeometry(QtCore.QRect(120, 757, 121, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.date.setFont(font)
        self.date.setStyleSheet(_fromUtf8("color: black;\n"
"border :0px;\n"
"background-color:rgb(255, 239, 229);"))
        self.date.setText(_fromUtf8(""))
        self.date.setObjectName(_fromUtf8("date"))
        self.male = QtGui.QLabel(Dialog)
        self.male.setGeometry(QtCore.QRect(160, 680, 21, 20))
        self.male.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 229);\n"
"border-radius:0px;\n"
"border:0px solid black;"))
        self.male.setText(_fromUtf8(""))
        self.male.setObjectName(_fromUtf8("male"))
        self.female = QtGui.QLabel(Dialog)
        self.female.setGeometry(QtCore.QRect(220, 680, 21, 20))
        self.female.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 229);\n"
"border-radius:0px;\n"
"border:0px solid black;"))
        self.female.setText(_fromUtf8(""))
        self.female.setObjectName(_fromUtf8("female"))
        self.window1 = QtGui.QLabel(Dialog)
        self.window1.setGeometry(QtCore.QRect(290, 120, 551, 701))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.window1.setFont(font)
        self.window1.setStyleSheet(_fromUtf8("background-color:white;\n"
"border-radius:20px;\n"
"border:2px solid black;"))
        self.window1.setText(_fromUtf8(""))
        self.window1.setObjectName(_fromUtf8("window1"))
        self.video_text = QtGui.QLabel(Dialog)
        self.video_text.setGeometry(QtCore.QRect(310, 150, 161, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.video_text.setFont(font)
        self.video_text.setStyleSheet(_fromUtf8("border: 3px solid rgb(129, 1, 3);\n"
"border-radius:10px;\n"
"background-color:rgb(139, 0, 41);\n"
"color:white;"))
        self.video_text.setAlignment(QtCore.Qt.AlignCenter)
        self.video_text.setObjectName(_fromUtf8("video_text"))
        self.ON = QtGui.QLabel(Dialog)
        self.ON.setGeometry(QtCore.QRect(735, 155, 21, 21))
        self.ON.setStyleSheet(_fromUtf8("color:black;"))
        self.ON.setText(_fromUtf8(""))
        self.ON.setObjectName(_fromUtf8("ON"))
        self.OFF = QtGui.QLabel(Dialog)
        self.OFF.setGeometry(QtCore.QRect(805, 155, 21, 21))
        self.OFF.setStyleSheet(_fromUtf8("\n"
"color:black;"))
        self.OFF.setText(_fromUtf8(""))
        self.OFF.setObjectName(_fromUtf8("OFF"))
        self.pushButton_pre = QtGui.QPushButton(Dialog)
        self.pushButton_pre.setGeometry(QtCore.QRect(620, 140, 211, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_pre.setFont(font)
        self.pushButton_pre.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"border-radius:10px;\n"
""))
        self.pushButton_pre.setObjectName(_fromUtf8("pushButton_pre"))
        self.box1 = QtGui.QLabel(Dialog)
        self.box1.setGeometry(QtCore.QRect(310, 210, 511, 491))
        self.box1.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.box1.setText(_fromUtf8(""))
        self.box1.setObjectName(_fromUtf8("box1"))
        self.Axial_label = QtGui.QLabel(Dialog)
        self.Axial_label.setGeometry(QtCore.QRect(350, 220, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Axial_label.setFont(font)
        self.Axial_label.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.Axial_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Axial_label.setObjectName(_fromUtf8("Axial_label"))
        self.Coronal_label = QtGui.QLabel(Dialog)
        self.Coronal_label.setGeometry(QtCore.QRect(520, 220, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Coronal_label.setFont(font)
        self.Coronal_label.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.Coronal_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Coronal_label.setObjectName(_fromUtf8("Coronal_label"))
        self.Sagittal_label = QtGui.QLabel(Dialog)
        self.Sagittal_label.setGeometry(QtCore.QRect(690, 220, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Sagittal_label.setFont(font)
        self.Sagittal_label.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.Sagittal_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Sagittal_label.setObjectName(_fromUtf8("Sagittal_label"))
        self.Axial = QtGui.QLabel(Dialog)
        self.Axial.setGeometry(QtCore.QRect(320, 260, 151, 201))
        self.Axial.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.Axial.setText(_fromUtf8(""))
        self.Axial.setObjectName(_fromUtf8("Axial"))
        self.jpg1 = QtGui.QLabel(Dialog)
        self.jpg1.setGeometry(QtCore.QRect(320, 480, 151, 201))
        self.jpg1.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.jpg1.setText(_fromUtf8(""))
        self.jpg1.setObjectName(_fromUtf8("jpg1"))
        self.Coronal = QtGui.QLabel(Dialog)
        self.Coronal.setGeometry(QtCore.QRect(490, 260, 151, 201))
        self.Coronal.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.Coronal.setText(_fromUtf8(""))
        self.Coronal.setObjectName(_fromUtf8("Coronal"))
        self.Sagittal = QtGui.QLabel(Dialog)
        self.Sagittal.setGeometry(QtCore.QRect(660, 260, 151, 201))
        self.Sagittal.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.Sagittal.setText(_fromUtf8(""))
        self.Sagittal.setObjectName(_fromUtf8("Sagittal"))
        self.jpg2 = QtGui.QLabel(Dialog)
        self.jpg2.setGeometry(QtCore.QRect(490, 480, 151, 201))
        self.jpg2.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.jpg2.setText(_fromUtf8(""))
        self.jpg2.setObjectName(_fromUtf8("jpg2"))
        self.jpg3 = QtGui.QLabel(Dialog)
        self.jpg3.setGeometry(QtCore.QRect(660, 480, 151, 201))
        self.jpg3.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.jpg3.setText(_fromUtf8(""))
        self.jpg3.setObjectName(_fromUtf8("jpg3"))
        self.result_text = QtGui.QLabel(Dialog)
        self.result_text.setGeometry(QtCore.QRect(890, 630, 161, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.result_text.setFont(font)
        self.result_text.setStyleSheet(_fromUtf8("border: 3px solid rgb(129, 1, 3);\n"
"border-radius:10px;\n"
"background-color:rgb(139, 0, 41);\n"
"color:white;"))
        self.result_text.setAlignment(QtCore.Qt.AlignCenter)
        self.result_text.setObjectName(_fromUtf8("result_text"))
        self.box2 = QtGui.QLabel(Dialog)
        self.box2.setGeometry(QtCore.QRect(890, 690, 581, 111))
        self.box2.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.box2.setText(_fromUtf8(""))
        self.box2.setObjectName(_fromUtf8("box2"))
        self.Rventricle = QtGui.QLabel(Dialog)
        self.Rventricle.setGeometry(QtCore.QRect(315, 730, 21, 17))
        self.Rventricle.setStyleSheet(_fromUtf8("background-color:white;"))
        self.Rventricle.setText(_fromUtf8(""))
        self.Rventricle.setObjectName(_fromUtf8("Rventricle"))
        self.Rventricle_text = QtGui.QLabel(Dialog)
        self.Rventricle_text.setGeometry(QtCore.QRect(340, 730, 121, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.Rventricle_text.setFont(font)
        self.Rventricle_text.setStyleSheet(_fromUtf8("color:black;\n"
""))
        self.Rventricle_text.setText(_fromUtf8(""))
        self.Rventricle_text.setObjectName(_fromUtf8("Rventricle_text"))
        self.Lventricle_text = QtGui.QLabel(Dialog)
        self.Lventricle_text.setGeometry(QtCore.QRect(490, 730, 121, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.Lventricle_text.setFont(font)
        self.Lventricle_text.setStyleSheet(_fromUtf8("color:black;\n"
""))
        self.Lventricle_text.setText(_fromUtf8(""))
        self.Lventricle_text.setObjectName(_fromUtf8("Lventricle_text"))
        self.Lventricle = QtGui.QLabel(Dialog)
        self.Lventricle.setGeometry(QtCore.QRect(465, 730, 21, 17))
        self.Lventricle.setStyleSheet(_fromUtf8("background-color:white;"))
        self.Lventricle.setText(_fromUtf8(""))
        self.Lventricle.setObjectName(_fromUtf8("Lventricle"))
        self.Rcaudate = QtGui.QLabel(Dialog)
        self.Rcaudate.setGeometry(QtCore.QRect(610, 730, 21, 17))
        self.Rcaudate.setStyleSheet(_fromUtf8("background-color:white;"))
        self.Rcaudate.setText(_fromUtf8(""))
        self.Rcaudate.setObjectName(_fromUtf8("Rcaudate"))
        self.Rcaudate_text = QtGui.QLabel(Dialog)
        self.Rcaudate_text.setGeometry(QtCore.QRect(635, 730, 81, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.Rcaudate_text.setFont(font)
        self.Rcaudate_text.setStyleSheet(_fromUtf8("color:black;\n"
""))
        self.Rcaudate_text.setText(_fromUtf8(""))
        self.Rcaudate_text.setObjectName(_fromUtf8("Rcaudate_text"))
        self.window1_2 = QtGui.QLabel(Dialog)
        self.window1_2.setGeometry(QtCore.QRect(870, 120, 621, 701))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.window1_2.setFont(font)
        self.window1_2.setStyleSheet(_fromUtf8("background-color:white;\n"
"border-radius:20px;\n"
"border:2px solid black;"))
        self.window1_2.setText(_fromUtf8(""))
        self.window1_2.setObjectName(_fromUtf8("window1_2"))
        self.analysis_text = QtGui.QLabel(Dialog)
        self.analysis_text.setGeometry(QtCore.QRect(890, 350, 161, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.analysis_text.setFont(font)
        self.analysis_text.setStyleSheet(_fromUtf8("border: 3px solid rgb(129, 1, 3);\n"
"border-radius:10px;\n"
"background-color:rgb(139, 0, 41);\n"
"color:white;"))
        self.analysis_text.setAlignment(QtCore.Qt.AlignCenter)
        self.analysis_text.setObjectName(_fromUtf8("analysis_text"))
        self.prob_text = QtGui.QLabel(Dialog)
        self.prob_text.setGeometry(QtCore.QRect(890, 150, 161, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.prob_text.setFont(font)
        self.prob_text.setStyleSheet(_fromUtf8("border: 3px solid rgb(129, 1, 3);\n"
"border-radius:10px;\n"
"background-color:rgb(139, 0, 41);\n"
"color:white;"))
        self.prob_text.setAlignment(QtCore.Qt.AlignCenter)
        self.prob_text.setObjectName(_fromUtf8("prob_text"))
        self.box3 = QtGui.QLabel(Dialog)
        self.box3.setGeometry(QtCore.QRect(890, 210, 341, 111))
        self.box3.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.box3.setText(_fromUtf8(""))
        self.box3.setObjectName(_fromUtf8("box3"))
        self.annotation1 = QtGui.QLabel(Dialog)
        self.annotation1.setGeometry(QtCore.QRect(1300, 280, 171, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.annotation1.setFont(font)
        self.annotation1.setStyleSheet(_fromUtf8("color:black;"))
        self.annotation1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.annotation1.setObjectName(_fromUtf8("annotation1"))
        self.annotation3 = QtGui.QLabel(Dialog)
        self.annotation3.setGeometry(QtCore.QRect(1300, 300, 171, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.annotation3.setFont(font)
        self.annotation3.setStyleSheet(_fromUtf8("color:black;"))
        self.annotation3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.annotation3.setObjectName(_fromUtf8("annotation3"))
        self.NC_text = QtGui.QLabel(Dialog)
        self.NC_text.setGeometry(QtCore.QRect(910, 240, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.NC_text.setFont(font)
        self.NC_text.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.NC_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.NC_text.setObjectName(_fromUtf8("NC_text"))
        self.AD_text = QtGui.QLabel(Dialog)
        self.AD_text.setGeometry(QtCore.QRect(910, 270, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.AD_text.setFont(font)
        self.AD_text.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.AD_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AD_text.setObjectName(_fromUtf8("AD_text"))
        self.Normal_plot = QtGui.QProgressBar(Dialog)
        self.Normal_plot.setGeometry(QtCore.QRect(990, 242, 141, 21))
        self.Normal_plot.setStyleSheet(_fromUtf8("QProgressBar {border:0px;background:rgb(255, 239, 229);} QProgressBar::chunk {background: rgb(139, 0, 41);}"))
        self.Normal_plot.setProperty("value", 0)
        self.Normal_plot.setTextVisible(False)
        self.Normal_plot.setOrientation(QtCore.Qt.Horizontal)
        self.Normal_plot.setObjectName(_fromUtf8("Normal_plot"))
        self.AD_plot = QtGui.QProgressBar(Dialog)
        self.AD_plot.setGeometry(QtCore.QRect(990, 270, 141, 23))
        self.AD_plot.setStyleSheet(_fromUtf8("QProgressBar {border:0px;background:rgb(255, 239, 229);} QProgressBar::chunk {background: rgb(139, 0, 41);}"))
        self.AD_plot.setProperty("value", 0)
        self.AD_plot.setTextVisible(False)
        self.AD_plot.setObjectName(_fromUtf8("AD_plot"))
        self.Normal_per = QtGui.QLabel(Dialog)
        self.Normal_per.setGeometry(QtCore.QRect(1150, 240, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Normal_per.setFont(font)
        self.Normal_per.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.Normal_per.setText(_fromUtf8(""))
        self.Normal_per.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Normal_per.setObjectName(_fromUtf8("Normal_per"))
        self.per1 = QtGui.QLabel(Dialog)
        self.per1.setGeometry(QtCore.QRect(1190, 240, 21, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.per1.setFont(font)
        self.per1.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.per1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.per1.setObjectName(_fromUtf8("per1"))
        self.AD_per = QtGui.QLabel(Dialog)
        self.AD_per.setGeometry(QtCore.QRect(1150, 270, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.AD_per.setFont(font)
        self.AD_per.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.AD_per.setText(_fromUtf8(""))
        self.AD_per.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AD_per.setObjectName(_fromUtf8("AD_per"))
        self.per3 = QtGui.QLabel(Dialog)
        self.per3.setGeometry(QtCore.QRect(1190, 270, 21, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.per3.setFont(font)
        self.per3.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.per3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.per3.setObjectName(_fromUtf8("per3"))
        self.reason_text1 = QtGui.QLabel(Dialog)
        self.reason_text1.setGeometry(QtCore.QRect(900, 700, 561, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.reason_text1.setFont(font)
        self.reason_text1.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.reason_text1.setText(_fromUtf8(""))
        self.reason_text1.setObjectName(_fromUtf8("reason_text1"))
        self.reason2_text1 = QtGui.QLabel(Dialog)
        self.reason2_text1.setGeometry(QtCore.QRect(900, 700, 561, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.reason2_text1.setFont(font)
        self.reason2_text1.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.reason2_text1.setText(_fromUtf8(""))
        self.reason2_text1.setObjectName(_fromUtf8("reason2_text1"))
        self.load = QtGui.QPushButton(Dialog)
        self.load.setGeometry(QtCore.QRect(50, 180, 201, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.load.setFont(font)
        self.load.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.load.setObjectName(_fromUtf8("load"))
        self.analysis = QtGui.QPushButton(Dialog)
        self.analysis.setGeometry(QtCore.QRect(50, 324, 201, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.analysis.setFont(font)
        self.analysis.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.analysis.setObjectName(_fromUtf8("analysis"))
        self.Lcaudate = QtGui.QLabel(Dialog)
        self.Lcaudate.setGeometry(QtCore.QRect(725, 730, 21, 17))
        self.Lcaudate.setStyleSheet(_fromUtf8("background-color:white;"))
        self.Lcaudate.setText(_fromUtf8(""))
        self.Lcaudate.setObjectName(_fromUtf8("Lcaudate"))
        self.Lcaudate_text = QtGui.QLabel(Dialog)
        self.Lcaudate_text.setGeometry(QtCore.QRect(750, 730, 71, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.Lcaudate_text.setFont(font)
        self.Lcaudate_text.setStyleSheet(_fromUtf8("color:black;\n"
""))
        self.Lcaudate_text.setText(_fromUtf8(""))
        self.Lcaudate_text.setObjectName(_fromUtf8("Lcaudate_text"))
        self.Rputamen = QtGui.QLabel(Dialog)
        self.Rputamen.setGeometry(QtCore.QRect(315, 750, 21, 17))
        self.Rputamen.setStyleSheet(_fromUtf8("background-color:white;"))
        self.Rputamen.setText(_fromUtf8(""))
        self.Rputamen.setObjectName(_fromUtf8("Rputamen"))
        self.Rputamen_text = QtGui.QLabel(Dialog)
        self.Rputamen_text.setGeometry(QtCore.QRect(340, 750, 81, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.Rputamen_text.setFont(font)
        self.Rputamen_text.setStyleSheet(_fromUtf8("color:black;\n"
""))
        self.Rputamen_text.setText(_fromUtf8(""))
        self.Rputamen_text.setObjectName(_fromUtf8("Rputamen_text"))
        self.Lputamen = QtGui.QLabel(Dialog)
        self.Lputamen.setGeometry(QtCore.QRect(465, 750, 21, 17))
        self.Lputamen.setStyleSheet(_fromUtf8("background-color:white;"))
        self.Lputamen.setText(_fromUtf8(""))
        self.Lputamen.setObjectName(_fromUtf8("Lputamen"))
        self.Lputamen_text = QtGui.QLabel(Dialog)
        self.Lputamen_text.setGeometry(QtCore.QRect(490, 750, 81, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.Lputamen_text.setFont(font)
        self.Lputamen_text.setStyleSheet(_fromUtf8("color:black;\n"
""))
        self.Lputamen_text.setText(_fromUtf8(""))
        self.Lputamen_text.setObjectName(_fromUtf8("Lputamen_text"))
        self.Rpallidum_text = QtGui.QLabel(Dialog)
        self.Rpallidum_text.setGeometry(QtCore.QRect(635, 750, 81, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.Rpallidum_text.setFont(font)
        self.Rpallidum_text.setStyleSheet(_fromUtf8("color:black;\n"
""))
        self.Rpallidum_text.setText(_fromUtf8(""))
        self.Rpallidum_text.setObjectName(_fromUtf8("Rpallidum_text"))
        self.Rpallidum = QtGui.QLabel(Dialog)
        self.Rpallidum.setGeometry(QtCore.QRect(610, 750, 21, 17))
        self.Rpallidum.setStyleSheet(_fromUtf8("background-color:white;"))
        self.Rpallidum.setText(_fromUtf8(""))
        self.Rpallidum.setObjectName(_fromUtf8("Rpallidum"))
        self.Lpallidum = QtGui.QLabel(Dialog)
        self.Lpallidum.setGeometry(QtCore.QRect(725, 750, 21, 17))
        self.Lpallidum.setStyleSheet(_fromUtf8("background-color:white;"))
        self.Lpallidum.setText(_fromUtf8(""))
        self.Lpallidum.setObjectName(_fromUtf8("Lpallidum"))
        self.Lpallidum_text = QtGui.QLabel(Dialog)
        self.Lpallidum_text.setGeometry(QtCore.QRect(750, 750, 81, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.Lpallidum_text.setFont(font)
        self.Lpallidum_text.setStyleSheet(_fromUtf8("color:black;\n"
""))
        self.Lpallidum_text.setText(_fromUtf8(""))
        self.Lpallidum_text.setObjectName(_fromUtf8("Lpallidum_text"))
        self.Lhippocampus_text = QtGui.QLabel(Dialog)
        self.Lhippocampus_text.setGeometry(QtCore.QRect(490, 770, 111, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.Lhippocampus_text.setFont(font)
        self.Lhippocampus_text.setStyleSheet(_fromUtf8("color:black;\n"
""))
        self.Lhippocampus_text.setText(_fromUtf8(""))
        self.Lhippocampus_text.setObjectName(_fromUtf8("Lhippocampus_text"))
        self.Ramygdala = QtGui.QLabel(Dialog)
        self.Ramygdala.setGeometry(QtCore.QRect(610, 770, 21, 17))
        self.Ramygdala.setStyleSheet(_fromUtf8("background-color:white;"))
        self.Ramygdala.setText(_fromUtf8(""))
        self.Ramygdala.setObjectName(_fromUtf8("Ramygdala"))
        self.Rhippocampus = QtGui.QLabel(Dialog)
        self.Rhippocampus.setGeometry(QtCore.QRect(315, 770, 21, 17))
        self.Rhippocampus.setStyleSheet(_fromUtf8("background-color:white;"))
        self.Rhippocampus.setText(_fromUtf8(""))
        self.Rhippocampus.setObjectName(_fromUtf8("Rhippocampus"))
        self.Rhippocampus_text = QtGui.QLabel(Dialog)
        self.Rhippocampus_text.setGeometry(QtCore.QRect(340, 770, 111, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.Rhippocampus_text.setFont(font)
        self.Rhippocampus_text.setStyleSheet(_fromUtf8("color:black;\n"
""))
        self.Rhippocampus_text.setText(_fromUtf8(""))
        self.Rhippocampus_text.setObjectName(_fromUtf8("Rhippocampus_text"))
        self.Lhippocampus = QtGui.QLabel(Dialog)
        self.Lhippocampus.setGeometry(QtCore.QRect(465, 770, 21, 17))
        self.Lhippocampus.setStyleSheet(_fromUtf8("background-color:white;"))
        self.Lhippocampus.setText(_fromUtf8(""))
        self.Lhippocampus.setObjectName(_fromUtf8("Lhippocampus"))
        self.Lamygdala = QtGui.QLabel(Dialog)
        self.Lamygdala.setGeometry(QtCore.QRect(725, 770, 21, 17))
        self.Lamygdala.setStyleSheet(_fromUtf8("background-color:white;"))
        self.Lamygdala.setText(_fromUtf8(""))
        self.Lamygdala.setObjectName(_fromUtf8("Lamygdala"))
        self.Ramygdala_text = QtGui.QLabel(Dialog)
        self.Ramygdala_text.setGeometry(QtCore.QRect(635, 770, 91, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.Ramygdala_text.setFont(font)
        self.Ramygdala_text.setStyleSheet(_fromUtf8("color:black;\n"
""))
        self.Ramygdala_text.setText(_fromUtf8(""))
        self.Ramygdala_text.setObjectName(_fromUtf8("Ramygdala_text"))
        self.Lamygdala_text = QtGui.QLabel(Dialog)
        self.Lamygdala_text.setGeometry(QtCore.QRect(750, 770, 81, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.Lamygdala_text.setFont(font)
        self.Lamygdala_text.setStyleSheet(_fromUtf8("color:black;\n"
""))
        self.Lamygdala_text.setText(_fromUtf8(""))
        self.Lamygdala_text.setObjectName(_fromUtf8("Lamygdala_text"))
        self.jpg4 = QtGui.QLabel(Dialog)
        self.jpg4.setGeometry(QtCore.QRect(900, 420, 175, 181))
        self.jpg4.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.jpg4.setText(_fromUtf8(""))
        self.jpg4.setObjectName(_fromUtf8("jpg4"))
        self.jpg5 = QtGui.QLabel(Dialog)
        self.jpg5.setGeometry(QtCore.QRect(1090, 420, 175, 181))
        self.jpg5.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.jpg5.setText(_fromUtf8(""))
        self.jpg5.setObjectName(_fromUtf8("jpg5"))
        self.jpg6 = QtGui.QLabel(Dialog)
        self.jpg6.setGeometry(QtCore.QRect(1280, 420, 175, 181))
        self.jpg6.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.jpg6.setText(_fromUtf8(""))
        self.jpg6.setObjectName(_fromUtf8("jpg6"))
        self.box4 = QtGui.QLabel(Dialog)
        self.box4.setGeometry(QtCore.QRect(890, 410, 581, 201))
        self.box4.setStyleSheet(_fromUtf8("background-color:rgb(255, 239, 225) ;\n"
"border-radius:15px;\n"
"color:black;"))
        self.box4.setText(_fromUtf8(""))
        self.box4.setObjectName(_fromUtf8("box4"))
        self.analysis_text_2 = QtGui.QLabel(Dialog)
        self.analysis_text_2.setGeometry(QtCore.QRect(1060, 365, 351, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.analysis_text_2.setFont(font)
        self.analysis_text_2.setStyleSheet(_fromUtf8("\n"
"background-color:white;\n"
"color:black;"))
        self.analysis_text_2.setAlignment(QtCore.Qt.AlignCenter)
        self.analysis_text_2.setObjectName(_fromUtf8("analysis_text_2"))
        self.window1_2.raise_()
        self.box4.raise_()
        self.load_back.raise_()
        self.label.raise_()
        self.korea.raise_()
        self.iitp.raise_()
        self.analysis_back.raise_()
        self.text_back.raise_()
        self.patient_info.raise_()
        self.id_text.raise_()
        self.name_text.raise_()
        self.sex_text.raise_()
        self.birth_text.raise_()
        self.date_text.raise_()
        self.id.raise_()
        self.name.raise_()
        self.sex.raise_()
        self.birth.raise_()
        self.date.raise_()
        self.male.raise_()
        self.female.raise_()
        self.window1.raise_()
        self.video_text.raise_()
        self.pushButton_pre.raise_()
        self.ON.raise_()
        self.OFF.raise_()
        self.box1.raise_()
        self.Axial_label.raise_()
        self.Coronal_label.raise_()
        self.Sagittal_label.raise_()
        self.Axial.raise_()
        self.jpg1.raise_()
        self.Coronal.raise_()
        self.Sagittal.raise_()
        self.jpg2.raise_()
        self.jpg3.raise_()
        self.Rventricle.raise_()
        self.Rventricle_text.raise_()
        self.Lventricle_text.raise_()
        self.Lventricle.raise_()
        self.Rcaudate.raise_()
        self.Rcaudate_text.raise_()
        self.analysis_text.raise_()
        self.prob_text.raise_()
        self.box3.raise_()
        self.annotation1.raise_()
        self.annotation3.raise_()
        self.NC_text.raise_()
        self.AD_text.raise_()
        self.Normal_plot.raise_()
        self.AD_plot.raise_()
        self.Normal_per.raise_()
        self.per1.raise_()
        self.AD_per.raise_()
        self.per3.raise_()
        self.load.raise_()
        self.analysis.raise_()
        self.Lcaudate.raise_()
        self.Lcaudate_text.raise_()
        self.Rputamen.raise_()
        self.Rputamen_text.raise_()
        self.Lputamen.raise_()
        self.Lputamen_text.raise_()
        self.Rpallidum_text.raise_()
        self.Rpallidum.raise_()
        self.Lpallidum.raise_()
        self.Lpallidum_text.raise_()
        self.Lhippocampus_text.raise_()
        self.Ramygdala.raise_()
        self.Rhippocampus.raise_()
        self.Rhippocampus_text.raise_()
        self.Lhippocampus.raise_()
        self.Ramygdala_text.raise_()
        self.Lamygdala_text.raise_()
        self.Lamygdala.raise_()
        self.result_text.raise_()
        self.box2.raise_()
        self.jpg4.raise_()
        self.jpg5.raise_()
        self.jpg6.raise_()
        self.reason_text1.raise_()
        self.reason2_text1.raise_()
        self.analysis_text_2.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "MR 영상 기반 알츠하이머 진단 딥러닝 모델", None))
        self.label.setText(_translate("Dialog", "MR 영상 기반 알츠하이머 진단 딥러닝 모델", None))
        self.patient_info.setText(_translate("Dialog", "환자 정보", None))
        self.id_text.setText(_translate("Dialog", "ID", None))
        self.name_text.setText(_translate("Dialog", "이름", None))
        self.sex_text.setText(_translate("Dialog", "성별", None))
        self.birth_text.setText(_translate("Dialog", "생년월일", None))
        self.date_text.setText(_translate("Dialog", "진료일", None))
        self.sex.setText(_translate("Dialog", "남 성      여성", None))
        self.video_text.setText(_translate("Dialog", "MR 영상", None))
        self.pushButton_pre.setText(_translate("Dialog", "전처리   ON      OFF    ", None))
        self.Axial_label.setText(_translate("Dialog", "Axial", None))
        self.Coronal_label.setText(_translate("Dialog", "Coronal", None))
        self.Sagittal_label.setText(_translate("Dialog", "Sagittal", None))
        self.result_text.setText(_translate("Dialog", "진단 보고서", None))
        self.analysis_text.setText(_translate("Dialog", "주요영역 분석", None))
        self.prob_text.setText(_translate("Dialog", "진단 확률", None))
        self.annotation1.setText(_translate("Dialog", "*NC: Normal Condition", None))
        self.annotation3.setText(_translate("Dialog", "**AD: Alzheimer\'s Disease", None))
        self.NC_text.setText(_translate("Dialog", "NC", None))
        self.AD_text.setText(_translate("Dialog", "AD", None))
        self.per1.setText(_translate("Dialog", "%", None))
        self.per3.setText(_translate("Dialog", "%", None))
        self.load.setText(_translate("Dialog", "MR 영상\n"
"불러오기", None))
        self.analysis.setText(_translate("Dialog", "MR 영상\n"
"분석하기", None))
        self.analysis_text_2.setText(_translate("Dialog", "딥러닝 기반 진단결과에 영향을 미친 주요영역 시각화", None))

